name: openid_client_fork
description: Fork of openid_client
version: 0.5.0
homepage: https://github.com/zweidenker/openid_client_fork

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  jose: ^0.3.2
  pointycastle: ^3.0.0
  http: ^0.13.0
  logging: ^1.0.0
  args: ^2.0.0
  meta: ^1.0.0

dev_dependencies:
  test: ^1.16.5
  pedantic: ^1.11.0

executables:
  openid_client: openid_client